---
title: "assignment"
output: html_document
date: "2024-09-09"
---

`
```{r}
library("tidyverse")

```
```{r}
supermat <- read.csv(file.choose())
```

```{r}
##Q 1: check the structure
str(supermat)
```


```{r}
## Q2 ;check for the number of rows
head(supermat)

```

```{r}
## Q3: check for the number of rows and columns in the dataset
nrow(supermat)
ncol(supermat)
```

```{r}
## Q4:get the names for columns in the dataset
colnames(supermat)

```

```{r}
## Q5:show how many females bought from production department
supermat %>%
  filter(Gender == "F" )%>%
  group_by(Product.Department)%>%
  summarise(count =n())
  

```

```{r}
  ##Q6; Get the total revenue made by the countries
rev_country <- supermat %>%
  group_by(Country)%>%
  summarise(total_rev =sum(Revenue))%>%
  arrange(desc(total_rev))
rev_country

```

```{r}
## Q7: Show the number of married and single people in the data set
supermat %>%
  group_by(Gender,Marital.Status)%>%
  summarise(count =n())

```

```{r}
#Q8 get the average revenue generated by the males in the dataset
supermat %>%
  filter(Gender == "M")%>%
  group_by(Marital.Status)%>%
  summarise(avg_rev =mean(Revenue))%>%
  arrange(avg_rev)

```

```{r}
# Q9 show how many females are home owners and the ones that are not
supermat %>%
  filter(Gender == "F")%>%
  group_by(Homeowner)%>%
summarise(count =n())
  

```

```{r}
# Q 10 show the number of males that are home owners and the ones that are not
supermat %>%
  filter(Gender == "M")%>%
  group_by(Homeowner)%>%
summarise(count =n())

```

```{r}
#Q 11 Show the average revenue by country
supermat %>%
  group_by(Country)%>%
  summarise(avg_rev = mean(Revenue))%>%
  arrange(avg_rev)
```

```{r}
#Q12: Get the total units sold by each country 
total_unit <- supermat %>%
  group_by(Country)%>%
  summarise(total_unit =sum(Units.Sold))%>%
  arrange(desc(total_unit))
total_unit
  
  
```

```{r}
 #Q13:show a bar graph of the categorical variable marital status and children
supermat %>%
  filter(Marital.Status == "M")%>%
  ggplot(aes(x=Children))+
  geom_histogram(binwidth = 4,color ="blue")
```

```{r}
#Q14:
supermat %>%
  group_by(Country) %>%
  summarise(count = round(sum(Revenue),0),
  show =paste0("$",round(count/10000,0),"K")) %>%
  ggplot(aes(x=Country, y=count, fill= Country))+
  geom_col()+
  geom_text(aes(x= Country, y= count, label= show),vjust="inward")
  

```

```{r}
#Q15 create a column chart to show all product category
supermat %>%
  group_by(Product.Department) %>%
  summarise(avg_p_rev = round(mean(supermat),2))%>%
  arrange(desc(avg_p_rev)) %>%
  ggplot(aes(x =reorder(Product.Department,avg_p_rev),y =avg_p_rev, fill =Product.Department))+
  geom_col()+
  coord_flip()+
  ylab("Average unit revenue per product department")
  xlab("product department")

```

```{r}
#Q16: show the annual income of the genders in a chart using ggplot
supermat %>%
  ggplot(aes(x= Gender, y= Annual.Income)) +
  geom_boxplot()

```

```{r}
#Q17 show a chart using geom jitter
supermat %>%
  ggplot(aes(x= Marital.Status, y= Product.Family)) +
  geom_jitter()
```

```{r}
#Q18:show a chart using geom point
supermat%>%
  ggplot(aes(x= Children, y= Annual.Income))+
  geom_point()
```

```{r}
#Q19 show the average unit sold by each country
supermat %>%
  group_by(Country) %>%
  summarise(avg_unit_sold =round(mean(Units.Sold),2)) %>%
  arrange(desc(avg_unit_sold))
```

```{r}
#Q20:create a column that shows the percentage revenue for each country
total_rev <-sum(supermat$Revenue)
supermat%>%
  group_by(Country)%>%
  summarise(total=sum(Revenue),percent=round(total/total_rev*100,2))

```

